development:
  adapter: solid_cable

test:
  adapter: test

production:
  adapter: solid_cable
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: students_connect_production
  database_url: <%= ENV["DATABASE_URL"] %>
